# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Included files
include:
- _redirects

# Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jemoji
- jekyll-feed

# SCSS
sass:
  style: :compressed

# Markdown
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty
paginate: 8

excerpt_separator: <!-- more -->

jekyll-mentions: https://twitter.com

timezone: Europe/London

# Site info
url: "https://david.darn.es"
title: "Dave's Blog"
name: "David Darnes"
description: "Articles about web design, development and some personal ones thrown in"
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=300"

# SEO > twitter name meta
twitter:
  username: DavidDarnes

# SEO > site name meta
social:
  name: "David Darnes"

# SEO > article author meta
author: DavidDarnes

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      icon: article
