# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jemoji

# SCSS
sass:
  style: :compressed

# Permalinks
permalink: pretty
paginate: 8

excerpt_separator: <!-- more -->

jekyll-mentions: https://twitter.com

# Site info
url: "https://david.darn.es"
title: "Dave's Blog"
name: "David Darnes"
description: "Articles about web design, development and some personal ones thrown in"
avatar: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=300"

# Networks
networks:
  Twitter: http://twitter.com/daviddarnes
  GitHub: http://github.com/daviddarnes
  CodePen: http://codepen.io/daviddarnes
  Dribbble: https://dribbble.com/daviddarnes

# Metadata
meta:
  facebook: daviddarnes
  twitter: DavidDarnes

# Defaults
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      is_page: true
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      is_post: true
      layout: post
      icon: article
