# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-sitemap
- jekyll-mentions
- jemoji

# SCSS
sass:
  style: :compressed

# Permalinks
permalink: pretty

jekyll-mentions: https://twitter.com

# Site info
url: "http://david.darn.es"
title: "Dave's Blog"
description: "Articles, tutorials and other ramblings from [David Darnes](https://darn.es)"
avatar: "http://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=144"

# Networks
networks:
  Twitter: http://twitter.com/daviddarnes
  GitHub: http://github.com/daviddarnes
  CodePen: http://codepen.io/daviddarnes
  Dribbble: https://dribbble.com/daviddarnes
